dist: xenial
language: ruby
services:
  - docker
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
gemfile:
  - gemfiles/activesupport_5.gemfile
  - gemfiles/activesupport_6.gemfile
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/activesupport_6.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/activesupport_6.gemfile

before_install: gem install bundler -v 2.2.16

script:
  - bundle exec rake spec_all
