name: Ruby CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        exclude:
          - ruby-version: 2.3.8
            gemfile: gemfiles/activesupport_6.gemfile
          - ruby-version: 2.4.10
            gemfile: gemfiles/activesupport_6.gemfile
        gemfile:
          - gemfiles/activesupport_5.gemfile
          - gemfiles/activesupport_6.gemfile
        ruby-version:
          - 2.3.8
          - 2.4.10
          - 2.5.8
          - 2.6.6
          - 2.7.2
          - '3.0.0' # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake spec_all
